"""create invoices table

Revision ID: 3b56b7af9113
Revises: e4d55a3a4ee4
Create Date: 2022-03-08 20:48:56.410989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b56b7af9113'
down_revision = 'e4d55a3a4ee4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###