"""create invoices table

Revision ID: 7e351c3dd1f7
Revises: 3b56b7af9113
Create Date: 2022-03-08 20:58:12.877605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e351c3dd1f7'
down_revision = '3b56b7af9113'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###