"""create invoices table

Revision ID: df676ab3179e
Revises: fd2cd8a949c5
Create Date: 2022-03-08 21:05:16.576623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df676ab3179e'
down_revision = 'fd2cd8a949c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###