"""create invoices table

Revision ID: e9cc76f8a4b1
Revises: 
Create Date: 2022-03-07 14:59:29.799024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9cc76f8a4b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoices', 'vendor',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index('ix_invoices_id', table_name='invoices')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_invoices_id', 'invoices', ['id'], unique=False)
    op.alter_column('invoices', 'vendor',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###