"""create invoices table

Revision ID: fd2cd8a949c5
Revises: 7e351c3dd1f7
Create Date: 2022-03-08 21:04:18.938216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd2cd8a949c5'
down_revision = '7e351c3dd1f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###